// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: mesh/mesh.proto

package mesh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeshMessage is the wire format for all ESP-NOW mesh frames (proto v1).
// New fields (8+) are additive — they do not change the encoding of fields 1-7.
type MeshMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field 1-7: unchanged from v0
	// 0=ADAPTER_DATA, 1=MASTER_BEACON, 2=ENROLLMENT, 3=JOIN_ACK
	MessageType uint32 `protobuf:"varint,1,opt,name=messageType,proto3" json:"messageType,omitempty"`
	// zigzag: -1=UNKNOWN, 0=PIR, 1=WIFI, 2=LED, 3=SERIAL
	DataType int32 `protobuf:"zigzag32,2,opt,name=dataType,proto3" json:"dataType,omitempty"`
	// 6 bytes
	OriginMacAddress []byte `protobuf:"bytes,3,opt,name=originMacAddress,proto3" json:"originMacAddress,omitempty"`
	// 6 bytes
	TargetMacAddress []byte `protobuf:"bytes,4,opt,name=targetMacAddress,proto3" json:"targetMacAddress,omitempty"`
	// 6 bytes
	LastHopMacAddress []byte `protobuf:"bytes,5,opt,name=lastHopMacAddress,proto3" json:"lastHopMacAddress,omitempty"`
	// up to 12 bytes
	Data     []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	HopCount uint32 `protobuf:"varint,7,opt,name=hopCount,proto3" json:"hopCount,omitempty"`
	// Security fields (proto v1, added alongside node firmware security update)
	// Must be 1 for all v1 messages
	ProtoVersion uint32 `protobuf:"varint,8,opt,name=protoVersion,proto3" json:"protoVersion,omitempty"`
	// Sender's boot epoch (persisted across reboots)
	EpochNum uint32 `protobuf:"varint,9,opt,name=epochNum,proto3" json:"epochNum,omitempty"`
	// Per-boot sequence counter (uint16 on device, uint32 here)
	SeqNum        uint32 `protobuf:"varint,10,opt,name=seqNum,proto3" json:"seqNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshMessage) Reset() {
	*x = MeshMessage{}
	mi := &file_mesh_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshMessage) ProtoMessage() {}

func (x *MeshMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshMessage.ProtoReflect.Descriptor instead.
func (*MeshMessage) Descriptor() ([]byte, []int) {
	return file_mesh_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *MeshMessage) GetMessageType() uint32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *MeshMessage) GetDataType() int32 {
	if x != nil {
		return x.DataType
	}
	return 0
}

func (x *MeshMessage) GetOriginMacAddress() []byte {
	if x != nil {
		return x.OriginMacAddress
	}
	return nil
}

func (x *MeshMessage) GetTargetMacAddress() []byte {
	if x != nil {
		return x.TargetMacAddress
	}
	return nil
}

func (x *MeshMessage) GetLastHopMacAddress() []byte {
	if x != nil {
		return x.LastHopMacAddress
	}
	return nil
}

func (x *MeshMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MeshMessage) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

func (x *MeshMessage) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

func (x *MeshMessage) GetEpochNum() uint32 {
	if x != nil {
		return x.EpochNum
	}
	return 0
}

func (x *MeshMessage) GetSeqNum() uint32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

// EnrollmentRequest is sent by master to server when a new node broadcasts a JOIN_REQUEST.
// Carried as a raw serial opcode frame (not protobuf-encoded), see serial.go.
type EnrollmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 6 bytes: MAC of the enrolling node
	Mac []byte `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	// 32 bytes: Curve25519 public key of the enrolling node
	PublicKey     []byte `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentRequest) Reset() {
	*x = EnrollmentRequest{}
	mi := &file_mesh_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentRequest) ProtoMessage() {}

func (x *EnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentRequest.ProtoReflect.Descriptor instead.
func (*EnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_mesh_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollmentRequest) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *EnrollmentRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// EnrollmentApproval is sent by server to master to approve a pending enrollment.
type EnrollmentApproval struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 6 bytes: MAC of the approved node
	Mac []byte `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	// 32 bytes: approved public key (echo for verification)
	PublicKey     []byte `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentApproval) Reset() {
	*x = EnrollmentApproval{}
	mi := &file_mesh_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentApproval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentApproval) ProtoMessage() {}

func (x *EnrollmentApproval) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentApproval.ProtoReflect.Descriptor instead.
func (*EnrollmentApproval) Descriptor() ([]byte, []int) {
	return file_mesh_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *EnrollmentApproval) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *EnrollmentApproval) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_mesh_mesh_proto protoreflect.FileDescriptor

// NOTE: This raw descriptor is hand-maintained to match the updated .proto file.
// It encodes the binary protobuf descriptor for the three messages above.
// Fields 8-10 (protoVersion, epochNum, seqNum) are added to MeshMessage.
// EnrollmentRequest and EnrollmentApproval are new messages.
// Regenerate with: protoc --go_out=. --go_opt=paths=source_relative mesh/mesh.proto
const file_mesh_mesh_proto_rawDesc = "" +
	"\n" +
	"\x0fmesh/mesh.proto\x12\x04mesh\"\xfa\x02\n" +
	"\vMeshMessage\x12 \n" +
	"\vmessageType\x18\x01 \x01(\rR\vmessageType\x12\x1a\n" +
	"\bdataType\x18\x02 \x01(\x11R\bdataType\x12*\n" +
	"\x10originMacAddress\x18\x03 \x01(\fR\x10originMacAddress\x12*\n" +
	"\x10targetMacAddress\x18\x04 \x01(\fR\x10targetMacAddress\x12,\n" +
	"\x11lastHopMacAddress\x18\x05 \x01(\fR\x11lastHopMacAddress\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x1a\n" +
	"\bhopCount\x18\a \x01(\rR\bhopCount\x12\"\n" +
	"\fprotoVersion\x18\x08 \x01(\rR\fprotoVersion\x12\x1a\n" +
	"\bepochNum\x18\t \x01(\rR\bepochNum\x12\x16\n" +
	"\x06seqNum\x18\n" +
	" \x01(\rR\x06seqNum\"F\n" +
	"\x11EnrollmentRequest\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\fR\x03mac\x12\x1c\n" +
	"\tpublicKey\x18\x02 \x01(\fR\tpublicKey\"G\n" +
	"\x12EnrollmentApproval\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\fR\x03mac\x12\x1c\n" +
	"\tpublicKey\x18\x02 \x01(\fR\tpublicKeyB,Z*github.com/superbrobenji/motionServer/meshb\x06proto3"

var (
	file_mesh_mesh_proto_rawDescOnce sync.Once
	file_mesh_mesh_proto_rawDescData []byte
)

func file_mesh_mesh_proto_rawDescGZIP() []byte {
	file_mesh_mesh_proto_rawDescOnce.Do(func() {
		file_mesh_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_mesh_proto_rawDesc), len(file_mesh_mesh_proto_rawDesc)))
	})
	return file_mesh_mesh_proto_rawDescData
}

var file_mesh_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mesh_mesh_proto_goTypes = []any{
	(*MeshMessage)(nil),        // 0: mesh.MeshMessage
	(*EnrollmentRequest)(nil),  // 1: mesh.EnrollmentRequest
	(*EnrollmentApproval)(nil), // 2: mesh.EnrollmentApproval
}
var file_mesh_mesh_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mesh_mesh_proto_init() }
func file_mesh_mesh_proto_init() {
	if File_mesh_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_mesh_proto_rawDesc), len(file_mesh_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mesh_mesh_proto_goTypes,
		DependencyIndexes: file_mesh_mesh_proto_depIdxs,
		MessageInfos:      file_mesh_mesh_proto_msgTypes,
	}.Build()
	File_mesh_mesh_proto = out.File
	file_mesh_mesh_proto_goTypes = nil
	file_mesh_mesh_proto_depIdxs = nil
}
